import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";
import Chatbox from "@/modules/chatbox/Chatbox";
// import dynamic from "next/dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MYXELLIA",
  description: "Generated by create next app",
};

// const Chatbox = dynamic(() => import('@/modules/chatbox/Chatbox'), {ssr: false})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full relative`}
      >
        <Topbar/>
        <Navbar/>
        {children}
        {/* <div className="absolute bottom-0 right-0"> */}
          <Chatbox/>
        {/* </div> */}
      </body>
    </html>
  );
}
